config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'cocktails#index'
  get 'cocktails' , to: 'cocktails#index', as: :cocktails
  resources :cocktails, only: [:index, :show, :new, :create] do
    resources :doses, only: [:index, :new, :create]
  end
  resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
validates :name, presence: :true, uniqueness: true
has_many :doses, dependent: :destroy
has_many :ingredients, through: :doses
has_one_attached :photo


end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates :cocktail_id, uniqueness: { scope: :ingredient_id }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_many:doses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [ :show ]

  def index
    @cocktails = Cocktail.all
  end

  def show


  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end


  # def update
 #   @cocktail= cocktail_find
  #  if @cocktail.update(cocktail_params)
   #   redirect_to cocktail_path
    #else
     # render :new
    #end


 # end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    # we need @restaurant in our `simple_form_for`
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end
  def create
    @dose = Dose.new(dose_params)
    # we need `restaurant_id` to associate review with corresponding restaurant
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end
  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end
  private
  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<div class="containerg">
  <h1>Cocktails!</h1>
</div>



<div class="container mt-4">
  <div class="cards">
    <%  @cocktails.each do |cocktail| %>
    <% if cocktail.photo.attached?%>
    <div class="card-category w-100" style="background-image:url(<%= cl_image_path cocktail.photo.key %>)">
      <% else %>
      <div class="card-category w-100" style="background-image:url(https://source.unsplash.com/1600x900/?<%= cocktail.name %>)">
      <% end %>
    <%= link_to cocktail.name, cocktail_path(cocktail), class: "link-cocktail" %>
    </div>
    <% end %>
    </div>
    </div>



    <div class="pad10 text-center">
      <%= link_to "Add your cocktail", new_cocktail_path, class: "btn btn-dark" %>
    </div>

app/views/cocktails/new.html.erb
<%= simple_form_for @cocktail do |f| %>
          <%= f.input :name %>
          <%= f.input :photo, as: :file %>
          <%= f.submit "Submit", class: "btn btn-dark" %>
        <% end %>

app/views/cocktails/show.html.erb
<div class = "life">
  <h2><%= @cocktail.name %></h2>
<%= link_to 'Back', cocktails_path %> |
<%= link_to 'Add dose', new_cocktail_dose_path(@cocktail) %>
</div>
<div class = "header">
<%  if @cocktail.photo.attached? %>
<%= cl_image_tag @cocktail.photo.key, height: 300, width: 400, crop: :fill %>
<% else %>
<img src="https://source.unsplash.com/1600x900/?<%= @cocktail.name %>" alt="Cocktail">
<% end %>
</div>
<div class = "container"></div>
  <div class ="jerk">
    <ul class="list-group">
      <% @cocktail.doses.each do |dose| %>
      <li class="list-group-item">
            <%= dose.description %>
            <%= dose.ingredient.name %>
            <%= link_to "Remove",
                        dose_path(dose),
                        method: :delete,
                        data: { confirm: "Are you sure?" } %>
      </li>
    </ul>
  <% end %>
  </div>
</div>

app/views/doses/new.html.erb
<%= simple_form_for [ @cocktail, @dose ] do |f| %>
  <%= f.input :description %>
  <%= f.association :ingredient %>
  <%= f.submit "Add new dose", class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>